// Code generated by protoc-gen-rest. DO NOT EDIT.
// source: pb/hello.proto

package pb


import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	runtime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	grpc "google.golang.org/grpc"
	context "golang.org/x/net/context"
)


// Server API for Say service
type sayServerClient struct {
	srv SayServer
}

func RegisterSayServerHandlerClient(ctx context.Context, mux *runtime.ServeMux, srv SayServer) error {
	return RegisterSayHandlerClient(ctx, mux, NewSayServerClient(srv))
}

func (h *sayServerClient) Hello(ctx context.Context, in *Request, _ ...grpc.CallOption) (*Response, error) {
	return h.srv.Hello(ctx, in)
}

func (h *sayServerClient) StartUpload(ctx context.Context, in *empty.Empty, _ ...grpc.CallOption) (*UploadRef, error) {
	return h.srv.StartUpload(ctx, in)
}

func (h *sayServerClient) CreatePhoto(ctx context.Context, in *CreatePhotoRequest, _ ...grpc.CallOption) (*Photo, error) {
	return h.srv.CreatePhoto(ctx, in)
}

func NewSayServerClient(srv SayServer) SayClient {
	return &sayServerClient{
		srv: srv,
	}
}

